name: Foundation
main: net.veilmc.dataapi.DataAPI
version: 0.1
author: sergivb01
description: DataAPI plugin
depend: [Construct]
commands:
  syncdata:
  sc:
    aliases: [staffchat]
  report:
  request:
    aliases: [helpop]
  staffserver:
  toggletab: